spring.application.name=PaintApplication
# spring.datasource.url=jdbc:mysql://localhost:3306/Paintdb
spring.datasource.username=root
spring.datasource.password=22011381
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

